#!/bin/sh
set +e
if command -v uicache >/dev/null 2>&1; then
    uicache -a >/dev/null 2>&1
elif [ -x /var/jb/usr/bin/uicache ]; then
    /var/jb/usr/bin/uicache -a >/dev/null 2>&1
fi
echo "finish:restart"
exit 0
